- readme.md
It's better than having an installation script.
> Add font installation instructions, fixes #5

- readme.md
> vim setup on os x

- plugin/webdevicons.vim
This also adds an `augroup` around it.
Ref: https://github.com/ryanoasis/vim-webdevicons/commit/203779dbbcc1e64ac21dbf454f26c92e7a079445#commitcomment-11019083
> Improve conceiling with NERDTree: replace closing bracket by space

- readme.md
Hi @ryanoasis,
This a little contribution, fixing the old link in README. Hope can contribute more, nice job with devicons! :beers:
> Change old link references

- plugin/webdevicons.vim
Hi @ryanoasis 
The second ruby icon looks great! What do you think to use this icon for default?
BTW, your job with vim-devicons is amazing ;)
> Suggestion: Change ruby icon for default

- plugin/webdevicons.vim
Hi @ryanoasis 
I'm adding some support for `.sql` and `.dump` files using same `db` icon. 
Hope you like. :beer:
> Add support for *.sql and dump files

- plugin/webdevicons.vim
Add support for `.ico` files (use same png icon)
> Support for .ico files

- readme.md
Set a folder where fonts are installed on Mac OSX.
> Improves install fonts intructions on mac

- plugin/webdevicons.vim
Hello again @ryanoasis :smile: 
I'm adding support for EJS files using same HTML icon. http://ejs.co/
BTW, every lang i'm using i will send here =p
> Add support for EJS files

- plugin/webdevicons.vim
> feat(unite): add file_rec/async and file_rec/neovim

- doc/webdevicons.txt
Fixes  #162
Open with neovim 
Neovim throws an error because of encoding.
#162
> fix(): E670 errors in neovim

- readme.md
N/A: Documentation Update
Fixes out of date info re: MRU mode for CtrP support. All modes are now supported in CtrlP, not just MRU mode.
See: https://github.com/ctrlpvim/ctrlp.vim/issues/313#issuecomment-253016657 for more info
> Update MRU mode support info.

- doc/webdevicons.txt
- readme.md
Resolve character encoding issues that prevent doc tags from being generated.
Replaces  dash `–` with a hyphen `-`.
#162
> fix(): fix character encoding

- doc/webdevicons.txt
- plugin/webdevicons.vim
- readme.md
Added yaml extension
-
The yaml extension is used a lot, probably even more then yml, so I have added it to the extension list.
> Added 'yaml' extenstion which is used quite common

- readme.md
Denite configuration documentation was missing from the readme. And an issue was raised about that and this PR is for fixing it.
preview PR
> Added missing Denite configuration to readme for fixing issue #205

- readme.md
Removes the duplicated LICENSE section of the README.md
N/A edited README.md
I saw this README.md suggested as a sample of a perfect README, it is amazing until the duplicated LICENSE section.
> Update README.md to remove duplicate

- .travis.yml
We can extend that later but I guess for now it's a good start.
Ref https://github.com/ryanoasis/vim-devicons/issues/122
> Add initial Travis CI with vim-vint linter

- plugin/webdevicons.vim
I add `gitlab` icon to resolve issue #292. 
Please check this Pull Request.
resolve #292 
Open `.gitlab-ci.yml`
> add gitlab icon

- .travis.yml
This Pull Request is to update python version in unit test.
Specifically, I upgraded the version from Python2 to Python3.
don't need.
> https://travis-ci.org/kazukazuinaina/vim-devicons/builds/642507585?utm_source=github_status&utm_medium=notification
Nothings
Nothings
> [update] python version in unit test

- plugin/webdevicons.vim
This PR resolve issue #304 
open .webp's filetype
Nothings.
Nothings
I wrote a patch to resolved issue #304.
Could you check this Pull Requset?
> [add] webp icon

- plugin/webdevicons.vim
check to can run `lsb_release -i`
#310 's PR
Could you check this Pull Request?
> [add] check can run 'lsb_release'

- .github/workflows/ci.yml
This patch is to update CI ( same test using vint ).
I suggest migrating from travis-ci to github-actions.
github-actions is much faster than travis-ci.
(The test is completed in just 7 seconds.)
Please see this status.
> https://github.com/kazukazuinaina/vim-devicons/runs/484550734
Nothings.
Nothings.
Nothings.
Could you check this Pull Request?
> [add] github_actions

- plugin/webdevicons.vim
This PR is supported for webmanifest's icon (like json).
Simply, open webmanifest's file.
related issue #321
> [add] webmanifest icon

- .github/workflows/ci.yml
- .github/workflows/vint.yml
- test/.themisrc
- test/fileformat.vim
- test/filetype.vim
I have introduced unit tests on the devicons global api. 
Static analysis by vint and execution of test code improve the quality of quality assurance.
1. Install and setting vim-themis
> https://github.com/thinca/vim-themis
2. run command below in devicons root dir
```bash
themis test
```
> https://github.com/kazukazuinaina/vim-devicons/runs/653510174
This shows the result of running the test on the forked repository.
- github-actions
- vim-themis
> [add] unit test

- plugin/webdevicons.vim
- test/default_setting.vim
- test/fileformat.vim
- test/filetype.vim
add function's name
this patch add devicon's config check
Nothig
Nothing
>  Add more check in devicons

- plugin/webdevicons.vim
- test/filetype.vim
Updated C# icon.
open C#'s file
I think this icon is more like C#.
> updated C# icon.

- plugin/webdevicons.vim
- test/filetype.vim
Unify React icons.
I only use '\ue7ba'
Nothing, see unit test's status.
> [Unification] react icon

- .github/workflows/ci.yml
change setup vim's tool
nothing
This patch can use cache.
> [adopt] thinca/action-setup-vim

- .github/workflows/ci.yml
Set the CI execution branch to master.
Nothing. Please see github-actions status.
Nothing.
> Set the CI execution branch to master.

- plugin/webdevicons.vim
This patch refactor  redundant nests.
Nothing.
> refactor airline's tabline

- .gitignore
updating .gitignore
Nothing
Nothing
Nothing
Nothing
> [update] gitignore

- plugin/webdevicons.vim
Add gentoo symbol
See Screenshots.
> Add gentoo symbol

- .github/workflows/ci.yml
I fixed CI's error.
Nothing. Please see CI's status.
> fix CI error

- .github/workflows/ci.yml
- .github/workflows/vint.yml
Update CI.
Nothing. Please see CI's status.
> https://github.com/actions/checkout/pull/305
> [update] github-actions

- autoload/airline/extensions/webdevicons.vim
- plugin/webdevicons.vim
I refactor airline's extension.
It improves the integration with vim-airline.
Starting Vim with vim-devicons and vim-airline.
#155
> [Refactoring] airline's extension

- test/filetype.vim
I add C# and F#'s symbol's test code.
Please see CI's status.
> [add] C# and F#'s test case

- plugin/webdevicons.vim
- test/filetype.vim
Fix #402 and #399 's issue
Please run `themis test`
> [fix] Resolve the issue where some icons are not displayed properly.

- test/filetype.vim
Made test function names explicit.
Like this.
`'Test condition 1'_'Test condition 2 (optional)'_'Expected result'`
themis test
> [fix] WebDevIconsGetFileTypeSymbol's test's function name

- test/filetype.vim
> [add] some test case

- plugin/webdevicons.vim
- test/filetype.vim
resolve https://github.com/ryanoasis/vim-devicons/issues/391 's issue.
themis test
> [add] .mk's test case

- .github/workflows/ci.yml
- test/filetype.vim
Update test to fix assertion roulette
themis test
> [fix] fix assertion roulette and [adopt] parameterized test for filetypesymbol's test

- test/filetype.vim
#412 and #413 's PR has been merged into master without test code.
Therefore, I wrote these test code.
Please run `themis test`
- #412
- #413
> Add missing testcase

- .github/workflows/ci.yml
- test/fileformat.vim
Some tests are skipped when the OS is not mac or ubuntu, because running tests locally sometimes fails.
Please run themis test
> Fix file format symbol test
