plugin/webdevicons.vim

I'm using Sauce Code Powerline Plus Nerd File Types, and just noticed that the Gopher disappeared. I installed the latest font from https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/SourceCodePro, and still got the generic icon, so I updated plugin/webdevicons.vim to use U+E724. That's the change below.

Fix glyph used for go

---

plugin/webdevicons.vim

Currently if you open up a directory in NERDtree with webdevicons before opening a file with conceal syntax, if the user has custom concealcursor/conceallevel settings they will be blown away by webdevicons

Use setlocal so as to not blow away user's config

---

plugin/webdevicons.vim

Hi @ryanoasis 
Some railers uses slim as default html template engine. This files ended with `.slim`, so i put slim in html icon as default. Hope you like it.

Add slim support

---

plugin/webdevicons.vim

Hi @ryanoasis 
Sorry for many PRs :sunglasses: 
Anyway, some libs like Octopress use `.markdown` extensions instead of `.md`. 
So, thats it. Hope you like. :+1:

Add .markdown support

---

plugin/webdevicons.vim

Mac OS X and above are designated with only `unix`

Add in system detect for fileformat on current macs

---

readme.md

~/.fonts has been deprecated for some time now, in favor of $XDG_DATA_HOME/fonts

use a non-deprecated font path for Linux fonts

---

plugin/webdevicons.vim
readme.md

The plugin is detecting Darwin by system `uname` command. But the `system()` call is too slow, and I noticed it makes the starting method slow, also. In this PR, `has('macunix')` is used for detecting Darwin instead of `system()` call.
You can see this with `+profile` feature.
```sh
vim --cmd "profile start profile.txt" --cmd "profile file /path/to/plugin/webdevicons.vim" +q && vim profile.txt
```
```vim
SCRIPT  /path/to/plugin/webdevicons.vim
Sourced 1 time
Total time:   0.286557
Self time:   0.001238
count  total (s)   self (s)
" Version: 0.7.0
" Webpage: https://github.com/ryanoasis/vim-devicons
" Maintainer: Ryan McIntyre <ryanoasis@gmail.com>
" License: see LICENSE
1              0.000003 let s:version = '0.7.0'
1   0.284813   0.000301 let s:operatingsystem = system("uname -s")
" …
```

Detect Darwin with lighter method

---

nerdtree_plugin/webdevicons.vim

NERDTree was returning an error when change root node because TreeFileNode.makeRoot() has been changed to NERDTree.changeRoot(node).

Fix NERDTree-C

---

plugin/webdevicons.vim

I have changed javascript.jsx file type to get [React](https://facebook.github.io/react/) icon, actually its hard to see icon for small font size but beneficial to select which file is js or jsx from buffer.

Update React (jsx) filetype icon

---

plugin/webdevicons.vim

Not really critical, but I've just noticed it.

WebDevIconsGetFileTypeSymbol: break if pattern matches

---

readme.md

adds reference to tiagofumo/vim-nerdtree-syntax-highlight on readme as talked with @ryanoasis on gitter
it's a readme file
I created this extension in another repo (because I thought I was going to be the only human being using it) and some people started caring about it, so I asked @ryanoasis if I should add reference to it on the readme's section and he said yes
https://github.com/ryanoasis/vim-devicons/issues/158#issuecomment-233814240
it's possible to see the output on my fork's page: https://github.com/tiagofumo/vim-devicons

add reference to tiagofumo/vim-nerdtree-syntax-highlight on readme

---

plugin/webdevicons.vim

The word “special” in the title, in this case means anything else that a normal buffer (a file). Additionally make sure we reset the alternate window as well so we can keep using that as expected.
For details why this fix is needed, please see this issue https://github.com/ctrlpvim/ctrlp.vim/issues/235 and the comments (mainly the last 5 or so) of this PR https://github.com/ctrlpvim/ctrlp.vim/pull/303
Also please see https://github.com/Xuyuanp/nerdtree-git-plugin/pull/63 as the related code was copied from there and they just merged the same fix as well. So this PR implements that same fix as users have reported the same issue when using this plugin as well.

Do not update when a special buffer is selected

---

readme.md

This is a quick documentation fix for plugin load order.
See: https://github.com/ryanoasis/vim-devicons/issues/168

Doc fix Plugin load order.

---

autoload/airline/extensions/tabline/formatters/webdevicons.vim

Gets rid of the extra space after an icon in airline.
There's an extra space after an icon in Airline that results in two spaces being added to the end of a tab title. There's only supposed to be one space there.

get rid of space after icon in airline

---

plugin/webdevicons.vim

Fix CtrlPBuffer name is [no named]
Install ctrlp + vimdevicon. Open multiple files. Open CtrlPBuffer
#183

fix ctrlp buffer name

---

plugin/webdevicons.vim

I have seen errors there when using `:set verbose=9 | set vfile=/tmp/vfile`.

Handle non-existing g:NERDTree in s:CursorHoldUpdate

---

plugin/webdevicons.vim
rplugin/python3/denite/filter/converter_devicons.py
rplugin/python3/denite/filter/devicons_denite_converter.py

Add support for the [denite plugin](https://github.com/Shougo/denite.nvim) 
works the same way as the unite converter, but denite requires any addons to be coded in python so that's what I did!

Added Denite Support

---

plugin/webdevicons.vim

Add the possibility to define a symbol to be displayed IF an utf-8 file contains a byte order marker (BOM)
- add
`let g:WebDevIconsUnicodeByteOrderMarkerDefaultSymbol = 'X'`
to your vimrc
- open any utf-8 file. If it has a bom, the X will show. If not:
`:set bomb`
The symbol used here is  /uE287

add symbol for byte order marker (utf-8)

---

plugin/webdevicons.vim

added several glyph to filename/type mappings

---

readme.md

This adds a link to [`vim-workspace`](https://github.com/bagrat/vim-workspace) in the readme, as an integrated plugin, that works with `vim-devicons` out-of-the box.
N/A
N/A
N/A

Add `vim-workspace` as an integrated plugin

---

readme.md

Fixes links
Review links
Was pointing at deprecated version
N/A
N/A

Consistently point to recommended version of CtrlP

---

plugin/webdevicons.vim

I don't know why this happens, but I just got a bug report vim-airline/vim-airline#1627 where an error is caused by trying to access `g:airline_section_x` which seems to be undefined for that user.
So here is a fix, that does not unconditionally access that variable, but only when it exists.
fixes vim-airline/vim-airline#1627
Thanks!

prevent error when g:airline_section_x is undefined

---

.gitignore
plugin/webdevicons.vim

This adds support to decorate directories that are symlinks with a different folder icon in nerdtree.
Start vim in a directory that has a symlink'd folder or create a test dir and symlink it somewhere.
While nerdtree already provides a way to see if a directory, it can be hard to read, especially if the path is pretty long. This small change is just a visual improvement.
None!

add support for symlink dirs

---

plugin/webdevicons.vim

`Dockerfile` and `docker-compose.yml` are recognized as Docker related
files.

Added support for Docker

---

plugin/webdevicons.vim
rplugin/python3/denite/filter/devicons_denite_converter.py

* Solve this issue https://github.com/ryanoasis/vim-devicons/issues/216
* Update sources to process like file_mru directory_mru
Enable denite and list buffers, file_mru, directory_mru, those are new features
https://github.com/ryanoasis/vim-devicons/issues/216

Keep all information from denite when adding icon

---

plugin/webdevicons.vim

Correction to a little error: `E15: Invalid expression: l.altwinnr . 'wincmd w'`
Solve this error:
```
Error detected while processing function <SNR>116_CursorHoldUpdate:
line   23:
E121: Undefined variable: l
Error detected while processing function <SNR>116_CursorHoldUpdate:
line   23:
E15: Invalid expression: l.altwinnr . 'wincmd w'
Executing CursorMoved Auto commands for "*"
```
Holding the cursor shows an error on the log.
Bug
none

Solving E15: Invalid expression

---

plugin/webdevicons.vim

The pull requests add support for .swift and .xcplayground files.
Can be tested by opening a .swift/.xcplayground file in (N)vi(M) with the plugin loaded.
Was a bit annoyed to find that Swift support was missing, especially as the primary occupation of Xcode is to act as a crash simulator.
nil
nil

add Swift icons

---

nerdtree_plugin/webdevicons.vim

When you open a directory on the nerdtree plugin the directory icon doesn't open. This PR permits to call the activatenode method on the single click, when the user try to open a directory.
Try to open a directory on nerdtree plugin. The icon will change with on the single click event.
I don't think you need other info.

Add leftrelease override to call the activatenode method on single click

---

README.md

Updates the name of the renamed `vim-buffet` (fka `vim-workspace`) plugin name in the README.
NA
NA
https://github.com/bagrat/vim-buffet/issues/14
NA

Replace vim-workspace with vim-buffet

---

plugin/webdevicons.vim

Adds support for 'mdx' markdown variant
Create a file with a `.mdx` extension and check the icon

Add support for mdx files

---

nerdtree_plugin/webdevicons.vim

This is a fix for the problem mentioned on https://github.com/ryanoasis/vim-devicons/pull/246#issuecomment-470973316
When the user has the g:NERDTreeMouseMode setted to  1, my previous pr override the 2clicks rule, so I added a new function to activate the node only if the g:NERDTreeMouseMode is setted to 3 (single click open any node).
Set g:NERDTreeMouseMode to 1 or 2 and the directory nodes are opened with double click, instead if you set g:NERDTreeMouseMode to 3 the directory nodes are opened with the single click and the icons work correctly.

#246: fix override when the g:NERDTreeMouseMode = 1

---

plugin/webdevicons.vim

Attempts to fix #248 and #223 remaining issues 
#248 & #223
<details>
</details>

WIP/RFC More nerdtree alignment consistency fixes (WIP for #248 and #223)

---

autoload/devicons/plugins/denite.vim

Denite.nvim was updated ver 3.0 and denite's api was changed but vim-devicons's denite api is old. Therefore, I fixed these api. And these patch also support old denite version.
#265

Adopt denite ver 3

---

autoload/devicons/plugins/denite.vim

Is there any reason while `file` is not among the sources for `denite`? Feel free to close if so, otherwise this PR fixes it.

show filetype icons in denite file source

---

plugin/webdevicons.vim

Resolve issue #282 
If you open .mjs file, JavaScript icon will be displayed
You open `.mjs` file.
Issue number #282

add mjs icon

---

nerdtree_plugin/webdevicons.vim

Fixes issue #276. Pressing \<CR\> on NERDTree to open/close a folder now toggles the folder icon.
Press \<CR\> on a folder in NERDTree.
On July 1st, NERDTree merged pull request [#1011](https://github.com/scrooloose/nerdtree/pull/1011) where new \<CR\> functionality was added.
There's now a `NERDTreeMapCustomOpen` mapping that handles `NERDTree-<CR>`, in addition to the already existing `NERDTreeMapActivateNode` that handled `NERDTree-o`, and it broke the toggling of the open/close folder icons.
According to the NERDTree help on `NERDTreeMapCustomOpen`:
> The default value matches what NERDTree-o does.
So, adding a key map to `NERDTreeMapCustomOpen` with the same callback parameter of `NERDTreeMapActivateNode` restores previous behavior, in which both `NERDTree-o` and `NERDTree-<CR>` …

Fix for issue #276 (the symbol for opened folder in NERDTree is not working)

---

plugin/webdevicons.vim

Resolve issue #284
If you open `.toml` file, gear icon will be displayed
You open `.toml` file.
Issue number #284

add toml file's icon

---

plugin/webdevicons.vim

I write this patch to resolve issue number #288 
Please check this Pull Request.
Resolve issue #288 
Open `.elm` flie
- vim-airline
- nerdtree

add elm icon

---

plugin/webdevicons.vim

I add `.cs` icon. Please check this Pull Request.
resolve #259 (**but I can't found `.css` icon in nerdfont**)
open .cs file

add .cs icon

---

autoload/airline/extensions/tabline/formatters/webdevicons.vim
doc/webdevicons.txt
plugin/webdevicons.vim

Added two new variables to configure how the vim-airline tabline shows the icons.
Just Installed, it should work as before. Changing the new variables should change how the name in the vim-airline tabline is shown. 
After changing to Kitty, I found a small problem with the icons.
From:
After changing: 
```
let g:WebDevIconsTabAirLineAfterGlyphPadding = ' '
let g:WebDevIconsTabAirLineBeforeGlyphPadding = ''
```
To:

Added configurable padding in vim-airline tabline

---

README.md

add ci status and fix nerdtree's url in document.
don't need
don't need
Hi, @ryanoasis .
I updated `README.md` to update nerdtree's url and add ci's status.
Could you check this Pull Request?

[update] nerdtree's url and [add] travis ci's badge 

---

plugin/webdevicons.vim

Fixed an error out put when re-sourcing vimrc and NERDTree plugin is lazy load
:source $MYVIMRC
Only happened if you use NERDTree as lazy load and not open NERDTree just yet, then re-soucing vimrc.

Fixed vim re-source vimrc bug when NERDTree is lazy load

---

plugin/webdevicons.vim

why not distinguish between different system icons when use unix operation system. Such as Arch, Ubuntu or Cent.
the command `lsb_release -i` will show what operation system you use.
```bash
$  lsb_release -i
Distributor ID:	Ubuntu
```
So, I just try to add some different icon when I use different linux. Now, I am using Arch.
Now, I can see the Arch logo.
And the icons can find in this. <https://raw.githubusercontent.com/just3ws/nerd-font-cheatsheets/master/font-linux.md>

To distinguish the system logo

---

plugin/webdevicons.vim

To avoid calling lsb_release each time what makes slow the editor
- [ x] I have read the [Contributing Guidelines](https://github.com/ryanoasis/vim-devicons/blob/master/contributing.md)
- [x ] I have read or at least glanced at the [FAQ](https://github.com/ryanoasis/vim-devicons#faq--troubleshooting)
- [ x] I have read or at least glanced at the [Wiki](https://github.com/ryanoasis/vim-devicons/wiki)
Fix slowness of editor on an upgrade on Linux distributions
Install the plugin and edit a file on Linux distribution

Cache lsb command

---

plugin/webdevicons.vim

I found that `Makefile` and `CMakeLists.txt` files were not sensible. So IMHO it's better to make their file icons to `` until [NerdFonts](https://github.com/ryanoasis/nerd-fonts) support these two filetypes.
Open `Makefile` and `CMakeLists.txt` files in vim.
Nothing
Nothing
Before:

Update make and cmake file icon

---

nerdtree_plugin/webdevicons.vim

This PR fixes the error with O and X in NERDTree not working correctly.
Use O and X in NERDTree before and after the patch.
#268 and #243

Fix error with O and X in NERDTree (Issue #268)

---

plugin/webdevicons.vim

Closes #278. Instead of concealing ALL brackets on a line, conceal only the ones surrounding the flags. These are identified by the NERDTreeFlags syntax group.
1. Create a file with square brackets in its name, ie. `[id].js`
1. Open NERDTree.
1. Verify the brackets in the name are still visible.
See #278. This PR replaces preservim/nerdtree#1111.
#278

Ensure only the brackets around the flags are concealed.

---

plugin/webdevicons.vim

This adds some more mappings to nicely display files from the ruby-world
- haml is a preprocessor for erb, commonly used in rails
- gemspec is the package-definition for rubygems
- rake contains code for rake-tasks, see Rakefile
- Rakefile is the equivalent of a Makefile for rake (a ruby make)
- config.ru is used by web-/app-servers as entrypoint
- Gemfile contains dependencies
The source-code of any rails-app should cover most of the files above.
If you have nothing at hand, try a checkout of https://github.com/hitobito/hitobito_generic, which contains those files in the project-root, in `lib/tasks/*.rake` and `app/views/people/*.haml`. https://github.com/hitobito/hitobito also contains a `config.ru` in the project-root.
Ruby is a language of careful balance. Its creator, Yukihiro “Matz” …

Add more files from the Ruby ecosystem

---

plugin/webdevicons.vim

Eliminate redundant nesting syntax and simplify the logic.
open the file with macOS or `set fileformat=unix`
Noting
Noting

[refactor] using ternary operators

---

plugin/webdevicons.vim

Add Nix Expression Language icon.
https://nixos.wiki/wiki/Nix_Expression_Language
Open .nix file.
nothing
nothing

[add] nix icon

---

plugin/webdevicons.vim
test/default_setting.vim

g:NERDTreeUpdateOnCursorHold has been renamed g:NERDTreeGitStatusUpdateOnCursorHold and gives a 'deprecated' warning on startup.
As of commit https://github.com/Xuyuanp/nerdtree-git-plugin/commit/31aaa3c1153dc8fc0f4f5aac4df5cc5243048bb5 some variables of nerdtree-git-plugin were renamed and marked as deprecated. With commit https://github.com/Xuyuanp/nerdtree-git-plugin/commit/c546443935d0d617d03347b0b8108295761559bc the default log level was changed to 'warning'. Now the use of deprecated variables triggers a warning message on startup.
This PR renames one variable (`g:NERDTreeUpdateOnCursorHold`) and stops the warning from being triggered.

NERDTree-Git variable has been renamed.

---

doc/webdevicons.txt
plugin/webdevicons.vim

It adds the `g:DevIconsEnableDistro` configuration option to control if the distribution icons should be shown when the file encoding is Unix.
Check if on a supported Linux distribution the distribution specific icon is shown in the default configuration and the generic icon (Tux) is used when `g:DevIconsEnableDistro` is set to `0`.
On my system `lsb_release -i` is really slow:
$ time lsb_release -i
Distributor ID:	Debian
lsb_release -i  0.93s user 0.07s system 100% cpu 1.003 total
Since I use this plugin together with [vim-airline](https://github.com/vim-airline/vim-airline), `lsb_release -i` is called on each startup to get the current distribution. This slows the startup down significantly.

Add option to disable showing distro for encoding

---

plugin/webdevicons.vim

This PR adds the a symbol for `.zshenv` and `.zprofile`. It coincides with that of `.zshrc` (a cog) for consistency.
Simply open `.zshrc` or `.zprofile`
It's been bugging me for a while that `.zshrc` gets a symbol while other special files don't.

Add icon for .zshenv and .zprofile

---

plugin/webdevicons.vim
test/filetype.vim

This pr is to fixed #393 issue.
```vim
1. :echo WebDevIconsGetFileTypeSymbol() -> 
2. :set ft=sh
3. :echo WebDevIconsGetFileTypeSymbol() ->  
```

Fix #393's issue

---

test/filetype.vim

[fix, add] test function name / add vimrc edit case for WebdevicnsFileTypeSymbol's API.

[fix, add] test function name / add vimrc edit case

---

plugin/webdevicons.vim

Add support for robots.txt as mentioned in issue #318.
Create a robots.txt file and observe it's file icon in nerdtree.
Clone my fork and observe the change.
Icon used is from [this comment](https://github.com/ryanoasis/vim-devicons/issues/318#issuecomment-615255775)
Issue #318 
One problem is this icon isn't supported by Cascadia Code. The above screenshot uses MesloLGF NF Regular font.

[add] support for robots.txt

---

plugin/webdevicons.vim

Display unix FreeBSB glyph when run on freebsd instead of the generic linux glyph
Launching *Vim on a BSD
First try, i modified s:getDistro that was a bad idea ; 
Second try, if check if there is "bsd" feature in case of unix fileformat.

Bsd feature

---

plugin/webdevicons.vim

The function implemented in #410 is out of the responsibility of the function.
Originally, I think the Linux icon should be handled in the `s:getDistro()` function. 
This problem has been fixed.
- #410

[fix] bsd feature in getdistro's function

---

plugin/webdevicons.vim
test/filetype.vim

Shows elixir icon for .heex files
Open .heex file
Phoenix added new template language [link to the blogpost](https://phoenixframework.org/blog/phoenix-1.6-released)

add .heex support

---

test/filetype.vim

Added some test cases for the WebDevIconsGetFileTypeSymbol() api.
- Case where no parameters are passed
- Case where two parameters are passed
Please run `themis test`

[add] some test in filetype
